// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyHXO-9GMETDet8KN5-aYBmB5bAgyxtPM',
    appId: '1:387719526233:web:7c1b1e366b4af28ddcfe48',
    messagingSenderId: '387719526233',
    projectId: 'my-travaly-demo',
    authDomain: 'my-travaly-demo.firebaseapp.com',
    storageBucket: 'my-travaly-demo.firebasestorage.app',
    measurementId: 'G-RNEYQP3JPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvss1Rsc6X83R3S1DkvmZixMMQgKVlmnQ',
    appId: '1:387719526233:android:acd1420ce1ef1295dcfe48',
    messagingSenderId: '387719526233',
    projectId: 'my-travaly-demo',
    storageBucket: 'my-travaly-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsIWcZJwLmhmd7fD60mYcrHgRcHG-KjAI',
    appId: '1:387719526233:ios:a1bd84843ce8c080dcfe48',
    messagingSenderId: '387719526233',
    projectId: 'my-travaly-demo',
    storageBucket: 'my-travaly-demo.firebasestorage.app',
    iosClientId: '387719526233-kem92m7v3k7uucm9goma9efmucoi8mhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTravalyDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsIWcZJwLmhmd7fD60mYcrHgRcHG-KjAI',
    appId: '1:387719526233:ios:a1bd84843ce8c080dcfe48',
    messagingSenderId: '387719526233',
    projectId: 'my-travaly-demo',
    storageBucket: 'my-travaly-demo.firebasestorage.app',
    iosClientId: '387719526233-kem92m7v3k7uucm9goma9efmucoi8mhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTravalyDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyHXO-9GMETDet8KN5-aYBmB5bAgyxtPM',
    appId: '1:387719526233:web:8d565175750a19e0dcfe48',
    messagingSenderId: '387719526233',
    projectId: 'my-travaly-demo',
    authDomain: 'my-travaly-demo.firebaseapp.com',
    storageBucket: 'my-travaly-demo.firebasestorage.app',
    measurementId: 'G-MYLRPWDQ0W',
  );
}
